### ISSUE TITLE
获取 encoded id 逻辑是否有误

### ISSUE THREAD

**Issue by edcmartin** [Wang-Yu-Qing/EGES#1]
https://github.com/Wang-Yu-Qing/EGES/blob/470876ac618081b9c9b16338d578b4c82e03df51/utils.py#L107-L116
若raw_id在之前出现过，返回的encoded id（自增）直接作为 raw id 的编码后的id 是否是 错误的

**Comment by Wang-Yu-Qing** [comment]
Yes you are right. I'm going to fix this.
